### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by mansya** [mike14u/croperino#33]
Hi, @ekimual I am a graphic designer, I want to help others in graphic design.
sorry for the closed issues. I accidentally clicked on it.
After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new icon / logo. what do you think? you want it?

**Comment by mike14u** [comment]
This is a non-issue, if you want to contribute icon / logo you can always do a pull request on the ReadMe. or email me personally.
